Resources page with routing
liimaorg/liima pull request #788
Opened 2024-11-05 09:46 UTC by llorentelemmc

2024-11-06 09:02 UTC, mburri requested changes

2024-11-06 09:02 UTC, mburri commented on AMW_rest/src/main/java/ch/mobi/itc/mobiliar/rest/resources/ResourceTypesRest.java
>          return resourceTypeDTOs;
replace with stream().map()

2024-11-06 09:02 UTC, mburri commented on AMW_rest/src/main/java/ch/mobi/itc/mobiliar/rest/resources/ResourceTypesRest.java
> +            resourceTypeDTOs.add(new ResourceTypeDTO(resourceType));
replace with stream().map()

2024-11-06 09:02 UTC, mburri commented on AMW_rest/src/main/java/ch/mobi/itc/mobiliar/rest/resources/ResourceTypesRest.java
> +        return resourceTypeDTOs;
replace with stream().map()

2024-11-06 09:04 UTC, mburri commented on AMW_business/src/main/java/ch/puzzle/itc/mobiliar/business/resourcegroup/boundary/ResourceTypeLocator.java
> +    }
`GET /thing/:id` should return 404 if the thing with the given id was not found
`GET /thing` should **not** return 404 if the list is empty

2024-11-13 08:16 UTC, BeriBoss commented on AMW_angular/io/src/app/resources/resources-page.component.html
> +      @if (expandedResourceTypeId === resourceType.id) {
```suggestion
      @if (resourceType.hasChildren && expandedResourceTypeId === resourceType.id) {
```

2024-11-28 13:25 UTC, merged