Feature/1022 codemirror v6
liimaorg/liima pull request #791
Opened 2024-11-07 10:13 UTC by StephGit

Adds code- and diff-editor-component
Fullscreen-Toggle (usefull for diff-view)
Refactor to use new app components
Fix and extend tests

2024-11-08 09:12 UTC, mburri commented on AMW_angular/io/src/app/settings/functions/function-edit.component.html
> +        <app-button [variant]="'secondary'" ngbDropdownToggle [dataCy]="'button-drpdown'">
drpdown -> dropdown?

2024-11-08 09:14 UTC, mburri commented on AMW_angular/io/src/styles.scss
> +*/
delete unused code?

2024-11-08 09:47 UTC, mburri requested changes
I think that the editor should be higher than only one line when you create a new function
![image](https://github.com/user-attachments/assets/93d843f8-ff37-4a6a-8a56-b6b4f960c8a3)

on the other hand, there should be probably an upper limit for the height?

![image](https://github.com/user-attachments/assets/a668163e-82d4-4110-a0b1-99a048638ccb)

2024-11-08 12:00 UTC, StephGit commented
> I think that the editor should be higher than only one line when you create a new function
> on the other hand, there should be probably an upper limit for the height?

made a fix for overflow/ height limit. 
quick fix with initial container size

2024-11-08 12:03 UTC, llorentelemmc commented
![Screenshot from 2024-11-08 12-54-45](https://github.com/user-attachments/assets/d8026f32-1dd7-46d5-9e7c-23b30e27d188)
![Screenshot from 2024-11-08 12-56-19](https://github.com/user-attachments/assets/c73713d6-21b6-46a6-9050-8fe64d7a1f9f)
In the new editor it's not immediately obvious which side is the current version.
Additionally, in the old editor only the current version was editable in the merge view.

2024-11-08 12:06 UTC, llorentelemmc commented on AMW_e2e/cypress/e2e/settings/functions/crud.cy.js
> +  it("should create, edit, compare and delete a function", () => {
You could also describe the new test scenario at the top of the file?

2024-11-11 09:37 UTC, llorentelemmc commented
![Screenshot from 2024-11-11 10-35-12](https://github.com/user-attachments/assets/43ba3e6a-a24f-4836-a0d2-b707bab2384a)
![Screenshot from 2024-11-11 10-31-08](https://github.com/user-attachments/assets/41bd56e4-8697-4fe4-83ad-0d96924d380b)
The revisions list is hidden when fullscreen toggle is selected

2024-11-11 16:21 UTC, StephGit commented
Rearranged ui to improve visibility of dropdown

2024-11-13 08:43 UTC, merged